public_repo_path=imgly/starterkit-photo-editor-android
public_repo_description=Photo Editor starter kit that is built on top of the Creative Editor SDK.
gradle_project_name=starter-kit-photo
app_name=Photo Editor
package_suffix=photo
